
services:
  postgres:
    image: bitnami/postgresql:latest
    volumes:
      - database:/bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_PORT_NUMBER=5432
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    depends_on:
      - postgres
    networks:
      - keycloak_network
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_DATABASE=bitnami_keycloak
      - DB_USER=postgres
      - DB_PASSWORD=postgres

volumes:
  database:

networks:
  keycloak_network:
    driver: bridge