@url = http://localhost:8080

###

GET {{url}}/campaings
Authorization: Bearer {{accessToken}}
###

GET {{url}}/campaings/cu3t8uri1v05mueb3ua0
Authorization: Bearer {{accessToken}}
###

PATCH  {{url}}/campaings/ctul1bbi1v0efviiog/cancel

###

PATCH {{url}}/campaings/cu3t8uri1v05mueb3ua0/start
Authorization: Bearer {{accessToken}}

###

DELETE {{url}}/campaings/ctul1bbi1v0efppviiog

###

POST {{url}}/campaings
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Teste de campanha",
  "content": "olá eu",
  "emails": [
    "renanalmeida2019.ra@gmail.com",
    "renanalmeida2015.ra@hotmail.com"
  ]
}

###
# @name token
POST http://localhost:8081/realms/providerGoEmail/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=projetoEmail&username=renanlira&password=123456&grant_type=password

###

@accessToken = {{token.response.body.access_token}}