@url = http://localhost:8080

###

GET {{url}}/campaings
Authorization: Bearer {{accessToken}}
###

GET {{url}}/campaings/ctul1bbi1v0efppvii

###

PATCH  {{url}}/campaings/ctul1bbi1v0efviiog/cancel

###

DELETE {{url}}/campaings/ctul1bbi1v0efppviiog

###

POST {{url}}/campaings
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Campaing1",
  "content": "Content 1",
  "emails": [
    "renan@email.com"
  ]
}

###
# @name token
POST http://localhost:8081/realms/providerGoEmail/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=projetoEmail&username=renanlira&password=123456&grant_type=password

###

@accessToken = {{token.response.body.access_token}}